### ISSUE TITLE
Create Documentation 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#22]
- [ ] Set up Read the Docs 
- [ ] Installation
- [ ] How to set the configs
- [ ] How to hook up with Song & Arranger

**Comment by blabadi** [comment]
Maestro documentation is up on read the docs (https://maestro-overture.readthedocs.io/en/latest/) and github pages (https://overture-stack.github.io/maestro/), I used markdown instead of rst because that thing was a pain to write with and with mark down I could build the gihub pages using the same md file

**Comment by rosibaj** [comment]
@blabadi All of our other documentation is written in rst - this helps render the side bar i think.  Can you please convert to rst so that we are consistent across the documentation (cc @alekspejovic)

**Comment by blabadi** [comment]
@rosibaj rst is really bad to write with and inefficient the requirement to be consistent was to use read the docs and I did that. I'll have to reject this request. my suggestion is to move away from old bad decisions and not stick to that, I don't see the point. for the navigation you can split into multiple md files but I didn't see that a big issue because it's small one

**Comment by alekspejovic** [comment]
@blabadi , for examples of how the other documentation was grouped into sections and formatted see:
- https://song-docs.readthedocs.io/en/develop/
- https://ego.readthedocs.io/en/latest/

Can we make sure it is organized into sections to conform with the other docs?

**Comment by blabadi** [comment]
@alekspejovic I can divide it into sections no problem

**Comment by alekspejovic** [comment]
Also @blabadi , are the document examples from ICGC. Can we avoid using real project names (PEME-CA) and data on the docs site as they are public?

**Comment by blabadi** [comment]
@alekspejovic that data is public too, I can change it though

**Comment by blabadi** [comment]
updated
