### ISSUE TITLE
Analysis of changes to Maestro for Dynamic Song

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#70]
- Currently maestro is configured to work with the relational song database
- What needs to be done to enable it to work with dynamic song?
- Develop a technical specification to update maestro

**Comment by rosibaj** [comment]
@blabadi Can you add any relevent details/gotchas about maestro here?

**Comment by Buwujiu** [comment]
Changes needed for Masetro:

The dynamic schema portion in SONG is called `data`, maestro needs to read the`data` portion in order to index analyses, studies, and repositories. 

- update `FileCentricAnalysis` model to use type : {name, version}
- update `FileCentricAnalysis` model, by replacing experiment field with `data` which will include the dynamic data portion
- update `FileCentricDocumentConverter.java ` . `getExperiement` method, to be `getData` method
